// Build the one-time seed SQL: players, the season's games, and any carried-over picks.
//   node scripts/build-seed.mjs [legacy-picks.json] > private/seed.sql
// Output goes to private/ (git-ignored) because carried-over picks for future weeks must not
// be readable in the public repo before those games kick off. Safe to re-run: upserts only.
import { readFileSync } from "node:fs";

const read = (p) => JSON.parse(readFileSync(new URL("../" + p, import.meta.url), "utf8"));
const schedule = read("data/schedule.json");
const players = read("data/players.json");
const legacyPath = process.argv[2];
const legacy = legacyPath ? JSON.parse(readFileSync(legacyPath, "utf8")) : {};

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const out = ["-- Generated by scripts/build-seed.mjs — run after schema.sql.", "begin;"];

out.push("insert into players(slug, name) values");
out.push(players.map((p) => `  (${q(p.slug)}, ${q(p.name)})`).join(",\n") +
  "\non conflict (slug) do update set name = excluded.name;");

const games = schedule.flatMap((w) => w.games.map((g) => ({ ...g, week: w.week, mnf: g.id === w.mnfGameId })));
out.push("insert into games(id, week, kickoff, is_mnf) values");
out.push(games.map((g) => `  (${q(g.id)}, ${g.week}, ${q(g.kickoff)}, ${g.mnf})`).join(",\n") +
  "\non conflict (id) do update set week = excluded.week, kickoff = excluded.kickoff, is_mnf = excluded.is_mnf;");

const gameIds = new Set(games.map((g) => g.id));
const pickRows = [], guessRows = [];
for (const doc of Object.values(legacy)) {
  for (const [gid, side] of Object.entries(doc.picks || {})) {
    if (!gameIds.has(gid)) throw new Error(`legacy pick for unknown game ${gid}`);
    pickRows.push(`  (${q(doc.slug)}, ${q(gid)}, ${q(side)}, ${q(doc.updatedAt || new Date().toISOString())})`);
  }
  if (doc.mnfGuess != null) guessRows.push(`  (${q(doc.slug)}, ${doc.week}, ${doc.mnfGuess}, ${q(doc.updatedAt || new Date().toISOString())})`);
}
if (pickRows.length) {
  out.push("insert into picks(player, game_id, side, updated_at) values");
  out.push(pickRows.join(",\n") + "\non conflict (player, game_id) do update set side = excluded.side, updated_at = excluded.updated_at;");
}
if (guessRows.length) {
  out.push("insert into guesses(player, week, mnf_guess, updated_at) values");
  out.push(guessRows.join(",\n") + "\non conflict (player, week) do update set mnf_guess = excluded.mnf_guess, updated_at = excluded.updated_at;");
}
out.push("commit;");
console.log(out.join("\n"));
console.error(`seed: ${players.length} players, ${games.length} games, ${pickRows.length} picks, ${guessRows.length} guesses`);
